//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProTrukRepo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public Nullable<decimal> ContractNo { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<int> Party { get; set; }
        public Nullable<double> TotatQty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> EcomID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual ContractType ContractType1 { get; set; }
        public virtual ExanaduCompany ExanaduCompany { get; set; }
        public virtual Party Party1 { get; set; }
    }
}
