//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProTrukRepo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dorder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dorder()
        {
            this.BiltyToDos = new HashSet<BiltyToDo>();
        }
    
        public decimal DoNumber { get; set; }
        public Nullable<decimal> ContractNumber { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<int> QTY { get; set; }
        public Nullable<int> GoodsType { get; set; }
        public string AddressEng { get; set; }
        public string AddressUrd { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> Party { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<decimal> Attached { get; set; }
        public Nullable<System.DateTime> DoDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> EcomID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiltyToDo> BiltyToDos { get; set; }
        public virtual City City { get; set; }
        public virtual ContractType ContractType1 { get; set; }
        public virtual GoodsType GoodsType1 { get; set; }
        public virtual Party Party1 { get; set; }
    }
}
