//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProTrukRepo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string EmailVeringCode { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int EcomID { get; set; }
        public string Picture { get; set; }
    
        public virtual ExanaduCompany ExanaduCompany { get; set; }
        public virtual Role Role { get; set; }
    }
}
