//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProTrukRepo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicle()
        {
            this.Drivers = new HashSet<Driver>();
            this.Bilties = new HashSet<Bilty>();
        }
    
        public int Id { get; set; }
        public string RegNumber { get; set; }
        public Nullable<int> Type { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> EcomID { get; set; }
        public Nullable<bool> IsContractorVehicle { get; set; }
        public Nullable<int> ContractorId { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilty> Bilties { get; set; }
    }
}
